name: cement_industries_dealer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  get:
  intl:
  dio:
  flutter_svg:
  flutter_spinkit:
  connectivity_plus:
  encrypt_shared_preferences:
  fluttertoast:
  freezed_annotation:
  json_annotation:
  syncfusion_flutter_core:
  syncfusion_flutter_charts:
  qr_code_scanner_plus:
  url_launcher:
  event_bus:
  dashed_circular_progress_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  freezed:
  very_good_analysis:
  json_serializable:
  flutter_native_splash:
  flutter_gen:

flutter_assets_generator:
  path_ignore: [ "ui/" ]

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/font/

  fonts:
    - family: hanken
      fonts:
        - asset: assets/font/if_hanken_black.ttf
          weight: 900
        - asset: assets/font/if_hanken_bold.ttf
          weight: 800
        - asset: assets/font/if_hanken_semibold.ttf
          weight: 700
        - asset: assets/font/if_hanken_medium.ttf
          weight: 600
        - asset: assets/font/if_hanken_regular.ttf
          weight: 500
        - asset: assets/font/if_hanken_light.ttf
          weight: 400


